apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  labels:
    app: project-name
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: project-name
  externalIPs:
    - 192.168.5.32
  ports:
    - port: 80
      name: "web"
      targetPort: web
      protocol: TCP
    - port: 443
      name: "websecure"
      targetPort: websecure
      protocol: TCP
