apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/version: "v3.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer # можно использовать NodePort, если у вас нет возможности использовать LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: traefik